elasticsearch:
  image: elasticsearch:2.2.1
  command: elasticsearch -Des.network.host=0.0.0.0
  ports:
    - "9200:9200"
    - "9300:9300"
logstash:
  image: logstash:2.2.2
  command: logstash -f /etc/logstash/conf.d/varel_serverlog-to-elastic.json
  volumes:
    - ./logstash/config:/etc/logstash/conf.d
    - ./logstash/logs:/etc/logstash/logs
  links:
    - elasticsearch
kibana:
  image: kibana:4.4.2
  volumes:
    - ./kibana/config/:/opt/kibana/config/
  ports:
    - "5601:5601"
  links:
    - elasticsearch
