version: '2'
services:
 elasticsearch:
   image: elasticsearch:2.2.1
   command: elasticsearch -Des.network.host=0.0.0.0
   ports:
     - "9200:9200"
     - "9300:9300"
   volumes:
     - ~/docker_composer_monitor_data/elasticsearch/data:/usr/share/elasticsearch/data
 logstash:
   image: viaeuropa/logstash-beats
   command: logstash -f /etc/logstash/conf.d/serverlog-to-elastic.json --debug
   volumes:
     - ./logstash/config:/etc/logstash/conf.d
   ports:
     - "5000:5000"
   links:
     - elasticsearch
 kibana:
   image: kibana:4.4.2
   volumes:
     - ./kibana/config/:/opt/kibana/config/
   ports:
     - "5601:5601"
   links:
     - elasticsearch
 filebeat:
   image: prima/filebeat:1.2.1
   command: filebeat -c /etc/filebeat/conf.d/filebeat.yml
   volumes:
     - ./filebeat/config/:/etc/filebeat/conf.d/
     - ~/docker_composer_monitor_data/filebeat/logs/:/etc/filebeat/logs/
     - ~/docker_composer_monitor_data/filebeat/logs_to_parse/varel/bicnet/:/usr/share/fileabeat/logs_to_parse/varel/bicnet/
   links:
     - logstash
 
