filebeat:
  registry_file: /etc/filebeat/logs/fb_registry.filebeat
  prospectors:
    -
      paths:
        - /usr/share/fileabeat/logs_to_parse/varel/bicnet/*
      document_type: varellog
output:
  logstash:
    hosts: ["logstash:5000"]
#  console:
#    pretty: true
shipper:
logging:
  level: error
  to_files: true
  to_syslog: false
  files:
    path: /etc/filebeat/logs
    name: beat.log
    rotateeverybytes: 10485760 # = 10MB
